language: rust
sudo: false

matrix:
  include:
  - env: JOB=test RUST_BACKTRACE=1
    dist: trusty
    rust: stable
    script:
    - cargo test --all --locked
    - rustup component add rustfmt-preview
    - cargo fmt --all -- --check

  - env: JOB=dist-linux
    dist: trusty
    rust: stable
    addons:
      apt:
        packages:
          - musl-tools
    install:
    - rustup target add x86_64-unknown-linux-musl
    - rustup target add i686-unknown-linux-musl
    script:
    - cargo build --release --target x86_64-unknown-linux-musl --locked
    - cargo build --release --target i686-unknown-linux-musl --locked

  - env: JOB=dist-osx
    os: osx
    rust: stable
    install:
    - rustup target add i686-apple-darwin
    script:
    - cargo build --release --target x86_64-apple-darwin --locked
    - cargo build --release --target i686-apple-darwin --locked

  - env: JOB=dist-windows
    os: windows
    rust: stable
    install:
    - rustup target add i686-pc-windows-msvc
    script:
    - cargo build --target x86_64-pc-windows-msvc --release --locked
    - cargo build --target i686-pc-windows-msvc --release --locked
