name: release

on:
  push:
    branches: ["test-release-*"]
    tags: ["v*"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - aarch64-unknown-linux-musl
        - x86_64-unknown-linux-musl
        - i686-unknown-linux-musl

    steps:
    - run: |
        uname -m
    - uses: actions/checkout@v4
    - name: Install toolchain
      run: |
        rustup set profile minimal
        rustup install stable
        rustup target add ${{ matrix.target }}
        rustup override set stable
    - name: Install cross
      run: |
        cargo install cross
    - name: Build target
      run: |
        cross build --release --target ${{ matrix.target }} --locked
    - run: |
        mkdir -p dist
        cp target/${{ matrix.target }}/release/clippy-reviewdog-filter dist/clippy-reviewdog-filter-${{ matrix.target }}
    - name: Upload artifacts for release
      uses: actions/upload-artifact@v4
      with:
        name: artifact-linux-${{ matrix.target }}
        path: dist
        if-no-files-found: error

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install toolchain
      run: |
        rustup set profile minimal
        rustup install stable
        rustup override set stable
    - name: Build for macOS (x86_64)
      run: cargo build --release --target x86_64-apple-darwin --locked
    - run: |
        mkdir -p dist
        cp target/x86_64-apple-darwin/release/clippy-reviewdog-filter dist/clippy-reviewdog-filter-x86_64-apple-darwin
    - name: Upload artifacts for release
      uses: actions/upload-artifact@v4
      with:
        name: artifact-macos
        path: dist
        if-no-files-found: error

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install toolchain
      run: |
        rustup set profile minimal
        rustup install stable
        # rustup target add x86_64-pc-windows-msvc
        rustup target add i686-pc-windows-msvc
        rustup override set stable
    - name: Build for Windows (x86_64)
      run: cargo build --release --target x86_64-pc-windows-msvc --locked
    - name: Build for Windows (x86)
      run: cargo build --release --target i686-pc-windows-msvc --locked
    - run: |
        mkdir -p dist
        cp target/x86_64-pc-windows-msvc/release/clippy-reviewdog-filter.exe dist/clippy-reviewdog-filter-x86_64-pc-windows-msvc.exe
        cp target/i686-pc-windows-msvc/release/clippy-reviewdog-filter.exe dist/clippy-reviewdog-filter-i686-pc-windows-msvc.exe
    - name: Upload artifacts for release
      uses: actions/upload-artifact@v4
      with:
        name: artifact-windows
        path: dist
        if-no-files-found: error

  create_release:
    name: Create Release
    needs: ["build-linux", "build-macos", "build-windows"]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts for release
        uses: actions/download-artifact@v4
        with:
          path: artifact
          pattern: artifact-*
          merge-multiple: true
      - run: find .
      - uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref }}
          body: Release ${{ github.ref }}
          draft: ${{ startsWith(github.ref, 'refs/heads/') }}
          prerelease: false
          files: |
            artifact/clippy-reviewdog-filter-*
