name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: ["1.75.0", stable, beta, nightly]

    steps:
    - uses: actions/checkout@v4
    - name: Install toolchain
      run: |
        rustup set profile minimal
        rustup install ${{ matrix.rust }}
        rustup override set ${{ matrix.rust }}
    - run: cargo test --all --locked
